# -*- coding: utf-8 -*-
"""Copy of עותק של karaoke.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ADifazBzcM6l9G0GS2az-SDl_J2MqFxb
"""

from flask import Flask, request, jsonify, send_from_directory
import os
import subprocess
import yt_dlp
import stable_whisper

app = Flask(__name__, static_folder='static')

# טעינת המודל פעם אחת כשהשרת עולה
print("טוען מודל AI...")
model = stable_whisper.load_model("large-v3", device="cuda")
os.makedirs("static", exist_ok=True)

@app.route('/')
def index():
    # מגיש את עמוד ה-HTML הראשי
    return send_from_directory('.', 'index.html')

@app.route('/api/create_karaoke', methods=['POST'])
def create_karaoke():
    data = request.json
    youtube_url = data.get('url')
    lyrics = data.get('lyrics')

    if not youtube_url or not lyrics:
        return jsonify({"error": "חסרים נתונים"}), 400

    # 1. הורדה מיוטיוב לתיקיית static
    audio_filename = "static/downloaded.wav"
    if os.path.exists(audio_filename): os.remove(audio_filename)

    ydl_opts = {
        'format': 'bestaudio/best',
        'postprocessors': [{'key': 'FFmpegExtractAudio', 'preferredcodec': 'wav'}],
        'outtmpl': 'static/downloaded.%(ext)s',
        'quiet': True
    }
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        ydl.download([youtube_url])

    # 2. הפרדת קולות
    subprocess.run(f'demucs -n htdemucs --two-stems=vocals "{audio_filename}" -o static/', shell=True, check=True)
    vocals_path = "static/htdemucs/downloaded/vocals.wav"
    instrumental_path = "static/htdemucs/downloaded/no_vocals.wav"

    # 3. סנכרון כפוי
    result = model.align(vocals_path, lyrics, language="he")

    # 4. עיבוד הנתונים למבנה שורות שה-HTML מבין (כמו שעשינו ב-Colab)
    flat_words = [{"word": w.word.strip(), "start": w.start, "end": w.end}
                  for s in result.segments for w in s.words if w.word.strip()]

    lines_data = []
    word_index = 0
    raw_lines = lyrics.strip('\n').split('\n')
    cleaned_lines = [line.strip() if line.strip() else "" for line in raw_lines]

    for line in cleaned_lines:
        if not line:
            lines_data.append({"is_empty": True, "words": []})
            continue
        line_word_count = len(line.split())
        line_words = [flat_words[word_index + i] for i in range(line_word_count) if word_index + i < len(flat_words)]
        word_index += line_word_count
        if line_words:
            lines_data.append({"is_empty": False, "start": line_words[0]["start"], "end": line_words[-1]["end"], "words": line_words})

    # מחזירים ל-HTML את הנתיב לשיר ואת התזמונים
    return jsonify({
        "audio_url": "/" + instrumental_path,
        "lyrics_data": lines_data
    })

if __name__ == '__main__':
    app.run(port=5000, debug=True)